### ISSUE TITLE
Manage Room - Add Group button not working

### ISSUE THREAD

**Issue by cbujara** [councilforeconed/interactive-activities#138]
Add Group button in Manage Room is not adding groups.

**Comment by cbujara** [comment]
Hello @jugglinmike! I recognize this isn't labeled as part of pizza productivity, but I am hoping we can tackle this in the current round of changes.

**Comment by jugglinmike** [comment]
Sure thing; I'll make this my next priority.

**Comment by jugglinmike** [comment]
Good news! This was an easy one--see gh-153

**Comment by cbujara** [comment]
Perfect!
