### ISSUE TITLE
Pizza Productivity Chart Issues

### ISSUE THREAD

**Issue by cbujara** [councilforeconed/interactive-activities#142]
In the chart displayed at the end of the pizza productivity simulation, the title for the y-axis overlays the numbers, making both illegible (see attached screenshot, from Firefox on OS X).

Also, it appears to be recording the number of chefs incorrectly. In the attached screenshot, it's showing activity for 6 chefs when only 4 were working. It's not clear how there could ever be more than 4 chefs.

![screen shot 2015-11-30 at 11 03 02 am](https://cloud.githubusercontent.com/assets/9950395/11476852/f520a80c-9752-11e5-8de3-e78513c1764e.png)

**Comment by jugglinmike** [comment]
> It's not clear how there could ever be more than 4 chefs.

The activity supports an arbitrary number of chefs; parameters like players-per-round and available-pizzas-per-round are derived according to the number of connected clients at any given time.

I only offer this as context, though: the behavior you've described is most definitely a bug.

**Comment by cbujara** [comment]
Tested in multiple rounds with multiple devices. Working perfectly now. Closing issue.

**Comment by jugglinmike** [comment]
Great!
