### ISSUE TITLE
Pizza productivity: no padding for "seconds" in countdown timer

### ISSUE THREAD

**Issue by jugglinmike** [councilforeconed/interactive-activities#145]
When the countdown timer is displaying less than 10 seconds remaining, it omits the leading zero typical in most digital clock faces:

![screenshot from 2015-12-08 11 30 39](https://cloud.githubusercontent.com/assets/677252/11661325/64412c14-9d9f-11e5-9641-c145ff44a107.png)

**Comment by cbujara** [comment]
Looks good!
