### ISSUE TITLE
Pizza productivity: no feedback for "completed" state

### ISSUE THREAD

**Issue by jugglinmike** [councilforeconed/interactive-activities#146]
When a pizza has been fully prepared for a given workstation, there is no
feedback that it can be advanced to the next station. Players are forced to
guess when they are done with a certain workstation. This is particularly
frustrating because releasing a pizza in an incomplete state reverts any
progress made.

Although this might be addressed by disallowing the release of incomplete
pizzas, that approach would have its own drawbacks. Specifically: players would
have to commit to completing a given pizza once they placed it on a
workstation. This would limit players' ability to alter their tactics.

Instead, give some visual indication that the pizza may advance.

**Comment by jugglinmike** [comment]
I vaguely recalled building something to this effect for the initial implementation, but it was clearly missing in the more recent versions. It turns out that (just like gh-138) the behavior was still present, but due to later UI refactoring by another developer, it was effectively disabled by incompatible changes to the layout.

In gh-160, we addressed those layout glitches, unintentionally re-enabling the indicator. Here's what it looks like on the `bocoup-2015` branch as of commit 9fd004973ed777f7d2be0ede6ba369fc46543c5c:

![done](https://cloud.githubusercontent.com/assets/677252/11940722/8027ccd6-a7f8-11e5-914a-1cd207c39d47.gif)

(Can you imagine if someone actually assembled your pizza like that?)

@cbujara This satisfies the concerns for usability that prompted me to create this issue, but the design itself seems a little ad-hoc. If you agree, maybe we should close this and open a new issue to discuss improvements to the visual design of the indicator?

**Comment by cbujara** [comment]
Ah, I'd seen that glowing green square, but I didn't make the connection that it indicated completion of a step. In fact, I only realized this morning that you didn't need to add everything in the ingredient bin to complete a step! Agreed that we should close this and add a nicetohave issue for a visual design improvement.
