### ISSUE TITLE
Charts resized incorrectly

### ISSUE THREAD

**Issue by jugglinmike** [councilforeconed/interactive-activities#147]
Some charts dynamically resize themselves in response to changes in viewport dimensions. These charts were authored to fill all available space exactly, but subsequent changes to the application layout have caused them to grow beyond the natural boundaries.

From the instructor report for the "Pizza Productivity" activity (note the superfluous horizontal scroll bar):

![screenshot from 2015-12-08 12 48 59](https://cloud.githubusercontent.com/assets/677252/11663588/2673c82c-9dab-11e5-8895-14e1f5e73ca5.png)

From the "When Graphs Mislead Us" activity:

![screenshot from 2015-12-08 12 50 48](https://cloud.githubusercontent.com/assets/677252/11663606/41be5f8e-9dab-11e5-8e14-29ddf40b9e83.png)

**Comment by cbujara** [comment]
Looking good!
